language: node_js
node_js:
  # Node.js
  - 'node'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  # io.js
  - '3'
  - '2'
  - '1'
  # Node.js
  - '0.12'
  - '0.10'
before_install:
  - npm update -g npm
after_script:
  - npm run coverage

