language: node_js
node_js:
  - 'stable'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
  - 'iojs'
before_install:
  - npm update -g npm
after_script:
  - npm run coverage

